/// Mock prospect generated by the AI profiling skill.
/// In production, this would come from Claude API web research.
class ProspectModel {
  final String id;
  final int rank;
  final String name;
  final String city;
  final String industry;
  final String sourceOfWealth;
  final String triggerEvent;
  final String? triggerDate;
  final String estNetWorthRange;
  final double wealthConfidence; // 1-5
  final double recencyScore;     // 1-5
  final double accessibilityScore; // 1-5
  final double fitScore;         // 1-5
  final double overallScore;     // weighted avg
  final String suggestedOutreachAngle;
  final String? keySources;

  const ProspectModel({
    required this.id,
    required this.rank,
    required this.name,
    required this.city,
    required this.industry,
    required this.sourceOfWealth,
    required this.triggerEvent,
    this.triggerDate,
    required this.estNetWorthRange,
    required this.wealthConfidence,
    required this.recencyScore,
    required this.accessibilityScore,
    required this.fitScore,
    required this.overallScore,
    required this.suggestedOutreachAngle,
    this.keySources,
  });

  /// Score color: green for 4+, amber for 3-4, red below 3
  String get scoreLabel {
    if (overallScore >= 4) return 'Strong';
    if (overallScore >= 3) return 'Moderate';
    return 'Low';
  }

  /// Pre-generated mock prospects for the profiling wizard.
  static List<ProspectModel> mockProspects() {
    return const [
      ProspectModel(
        id: 'PROS001', rank: 1,
        name: 'Anil Agarwal',
        city: 'Mumbai',
        industry: 'Mining & Metals',
        sourceOfWealth: 'Founder, Vedanta Resources — LSE-listed conglomerate',
        triggerEvent: 'Vedanta delisting bid re-initiated, significant promoter activity',
        triggerDate: 'Mar 2026',
        estNetWorthRange: '₹500-1000 Cr',
        wealthConfidence: 5, recencyScore: 4, accessibilityScore: 3, fitScore: 4,
        overallScore: 4.1,
        suggestedOutreachAngle: 'Delisting activity suggests liquidity event — approach via mining industry contacts for portfolio diversification discussion.',
      ),
      ProspectModel(
        id: 'PROS002', rank: 2,
        name: 'Priya Sharma (Tech)',
        city: 'Bangalore',
        industry: 'Technology / SaaS',
        sourceOfWealth: 'Co-founder, CloudPay — Series C exit to Stripe (USD 140M)',
        triggerEvent: 'Secondary sale of founder shares, post lock-up period',
        triggerDate: 'Feb 2026',
        estNetWorthRange: '₹100-250 Cr',
        wealthConfidence: 4, recencyScore: 5, accessibilityScore: 4, fitScore: 5,
        overallScore: 4.5,
        suggestedOutreachAngle: 'Fresh from exit — needs tax-efficient parking for proceeds. Likely interested in AIF/PMS. Approach via Bangalore tech network.',
      ),
      ProspectModel(
        id: 'PROS003', rank: 3,
        name: 'Rajesh Khanna',
        city: 'Delhi NCR',
        industry: 'Real Estate',
        sourceOfWealth: 'Promoter, Khanna Realty Group — 3 luxury projects in Gurgaon',
        triggerEvent: 'Sold 2 completed residential towers for ₹800 Cr aggregate',
        triggerDate: 'Jan 2026',
        estNetWorthRange: '₹200-500 Cr',
        wealthConfidence: 4, recencyScore: 4, accessibilityScore: 3, fitScore: 4,
        overallScore: 3.8,
        suggestedOutreachAngle: 'Real estate profit harvest — diversification into financial assets. Approach through property industry events.',
      ),
      ProspectModel(
        id: 'PROS004', rank: 4,
        name: 'Dr. Meera Patel',
        city: 'Hyderabad',
        industry: 'Pharma',
        sourceOfWealth: 'Founding family, Patel Pharma Ltd — listed on BSE',
        triggerEvent: 'Promoter stake sale 3% via bulk deal (₹150 Cr)',
        triggerDate: 'Mar 2026',
        estNetWorthRange: '₹50-100 Cr',
        wealthConfidence: 5, recencyScore: 5, accessibilityScore: 3, fitScore: 4,
        overallScore: 4.3,
        suggestedOutreachAngle: 'Fresh liquidity from stake sale. Pharma founders typically conservative — pitch structured products + fixed income.',
      ),
      ProspectModel(
        id: 'PROS005', rank: 5,
        name: 'Vikram Singh',
        city: 'Mumbai',
        industry: 'Financial Services',
        sourceOfWealth: 'Ex-Partner, McKinsey India — 25 years, now advisory board roles',
        triggerEvent: 'Joined board of two listed companies, appointed advisor to PE fund',
        triggerDate: 'Feb 2026',
        estNetWorthRange: '₹25-50 Cr',
        wealthConfidence: 3, recencyScore: 4, accessibilityScore: 5, fitScore: 4,
        overallScore: 3.9,
        suggestedOutreachAngle: 'High-access, well-networked professional. Approach for both personal wealth AND referral potential to his advisory clients.',
      ),
      ProspectModel(
        id: 'PROS006', rank: 6,
        name: 'Sunita Reddy',
        city: 'Chennai',
        industry: 'Manufacturing',
        sourceOfWealth: 'Promoter family, SRG Industries — auto components',
        triggerEvent: 'Family business succession — next-gen taking over, patriarch retiring',
        triggerDate: 'Q1 2026',
        estNetWorthRange: '₹75-150 Cr',
        wealthConfidence: 3, recencyScore: 3, accessibilityScore: 4, fitScore: 4,
        overallScore: 3.5,
        suggestedOutreachAngle: 'Succession event = wealth restructuring opportunity. Approach the retiring patriarch for legacy/estate planning.',
      ),
      ProspectModel(
        id: 'PROS007', rank: 7,
        name: 'Amit Joshi',
        city: 'Pune',
        industry: 'IT Services',
        sourceOfWealth: 'CTO exit from Infosys BPM, angel investor in 12 startups',
        triggerEvent: 'Lead investor in ₹50 Cr Series A for AI startup',
        triggerDate: 'Mar 2026',
        estNetWorthRange: '₹30-75 Cr',
        wealthConfidence: 3, recencyScore: 5, accessibilityScore: 4, fitScore: 4,
        overallScore: 3.9,
        suggestedOutreachAngle: 'Active angel — needs co-investment platform + portfolio hedging. Approach via Pune startup ecosystem.',
      ),
      ProspectModel(
        id: 'PROS008', rank: 8,
        name: 'Kavita Deshmukh',
        city: 'Mumbai',
        industry: 'Media & Entertainment',
        sourceOfWealth: 'Founder, StreamBox OTT — acquired by Zee for ₹200 Cr',
        triggerEvent: 'Earnout period complete, full proceeds received',
        triggerDate: 'Jan 2026',
        estNetWorthRange: '₹100-200 Cr',
        wealthConfidence: 4, recencyScore: 4, accessibilityScore: 4, fitScore: 5,
        overallScore: 4.3,
        suggestedOutreachAngle: 'Post-acquisition wealth — likely exploring next venture AND needs personal wealth management. Dual pitch: growth + preservation.',
      ),
    ];
  }

  /// Mock talking points for the RM to prepare for a pitch.
  static List<String> mockTalkingPoints(String leadName) {
    return [
      'Open with the prospect\'s recent wealth event — show you\'ve done your homework.',
      'Position JM as a one-stop wealth partner: PMS for alpha, AIF for alternatives, MF for core allocation.',
      'Discuss tax-efficient structuring for recent liquidity (capital gains, gift tax, trust structures).',
      'Mention JM\'s track record with similar HNW profiles in their industry vertical.',
      'Ask about their family\'s financial goals — inheritance planning, next-gen wealth education.',
    ];
  }
}
