import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:go_router/go_router.dart';
import '../../../../core/di/injection.dart';
import '../../../../core/enums/ib_deal_type.dart';
import '../../../../core/models/ib_lead_model.dart';
import '../../../../core/repositories/client_repository.dart';
import '../../../../core/repositories/ib_lead_repository.dart';
import '../../../../core/repositories/lead_repository.dart';
import '../../../../core/theme/app_colors.dart';
import '../../../../core/theme/app_text_styles.dart';
import '../../../../core/utils/inr_formatter.dart';
import '../../../../core/widgets/compass_empty_state.dart';
import '../../../../core/widgets/compass_loader.dart';
import '../../../../core/widgets/hero_app_bar.dart';
import '../../../../core/widgets/hero_scaffold.dart';
import '../../../auth/presentation/cubit/auth_cubit.dart';
import '../../../../routing/route_names.dart';

/// Consolidated view of every IB lead generated by the current RM:
///   (1) IB leads directly created by this RM (IbLeadRepository.getMyLeads)
///   (2) Wealth leads tagged as IB (ibLeadIds non-empty) for this RM
///   (3) Clients flagged hasIbLead == true for this RM
/// Merged and deduped by IB lead id. Syncs with the RM landing's "Sent Back"
/// widget via the same repository source.
class MyIbLeadsScreen extends StatefulWidget {
  const MyIbLeadsScreen({super.key});

  @override
  State<MyIbLeadsScreen> createState() => _MyIbLeadsScreenState();
}

class _MyIbLeadsScreenState extends State<MyIbLeadsScreen> {
  final IbLeadRepository _ibRepo = getIt<IbLeadRepository>();
  final LeadRepository _leadRepo = getIt<LeadRepository>();
  final ClientRepository _clientRepo = getIt<ClientRepository>();

  bool _loading = true;
  List<IbLeadModel> _leads = [];
  IbLeadStatus? _statusFilter;

  @override
  void initState() {
    super.initState();
    _load();
  }

  Future<void> _load() async {
    setState(() => _loading = true);
    final user = context.read<AuthCubit>().state.currentUser;
    if (user == null) return;

    final byMe = await _ibRepo.getMyLeads(user.id);
    final ids = <String>{for (final l in byMe) l.id};
    final merged = <IbLeadModel>[...byMe];

    // Wealth leads tagged as IB (by this RM) — resolve their child IB lead ids.
    try {
      final leadResult =
          await _leadRepo.getLeads(page: 1, pageSize: 500, assignedRmId: user.id);
      for (final lead in leadResult.items) {
        for (final ibId in lead.ibLeadIds) {
          if (ids.contains(ibId)) continue;
          final found = await _ibRepo.getById(ibId);
          if (found != null) {
            ids.add(ibId);
            merged.add(found);
          }
        }
      }
    } catch (_) {}

    // Clients with hasIbLead == true (for this RM). Not all client models carry
    // the IB lead id directly — if there's no linkage, we skip silently; the
    // lead-side scan above typically already covers these cases.
    try {
      final clientResult = await _clientRepo.getClients(
        page: 1,
        pageSize: 500,
        assignedRmId: user.id,
      );
      // Reserved for future: hasIbLead flag can resolve linked IB leads when
      // the client model gains an ibLeadIds field. For now this branch no-ops.
      // ignore: unused_local_variable
      final _ = clientResult;
    } catch (_) {}

    merged.sort((a, b) => b.createdAt.compareTo(a.createdAt));
    if (!mounted) return;
    setState(() {
      _leads = merged;
      _loading = false;
    });
  }

  List<IbLeadModel> get _filtered {
    if (_statusFilter == null) return _leads;
    return _leads.where((l) => l.status == _statusFilter).toList();
  }

  @override
  Widget build(BuildContext context) {
    final sentBack =
        _leads.where((l) => l.status == IbLeadStatus.sentBack).toList();

    return HeroScaffold(
      header: HeroAppBar.simple(
        title: 'My IB Leads',
        subtitle: '${_leads.length} total',
      ),
      body: _loading
          ? const Center(child: CompassLoader())
          : RefreshIndicator(
              color: AppColors.navyPrimary,
              onRefresh: _load,
              child: ListView(
                padding: const EdgeInsets.fromLTRB(14, 14, 14, 96),
                children: [
                  if (sentBack.isNotEmpty) _SentBackStrip(leads: sentBack),
                  if (sentBack.isNotEmpty) const SizedBox(height: 14),
                  _StatusFilterBar(
                    value: _statusFilter,
                    onChanged: (s) => setState(() => _statusFilter = s),
                    counts: _statusCounts(),
                  ),
                  const SizedBox(height: 12),
                  if (_filtered.isEmpty)
                    const CompassEmptyState(
                      icon: Icons.account_tree_outlined,
                      title: 'No IB leads yet',
                    )
                  else
                    ..._filtered.map(_buildCard),
                ],
              ),
            ),
    );
  }

  Map<IbLeadStatus, int> _statusCounts() {
    final map = <IbLeadStatus, int>{};
    for (final l in _leads) {
      map[l.status] = (map[l.status] ?? 0) + 1;
    }
    return map;
  }

  Widget _buildCard(IbLeadModel ib) {
    final statusColor = switch (ib.status) {
      IbLeadStatus.pending => AppColors.warmAmber,
      IbLeadStatus.approved => AppColors.successGreen,
      IbLeadStatus.sentBack => AppColors.errorRed,
      IbLeadStatus.forwarded => AppColors.tealAccent,
      _ => AppColors.textHint,
    };
    return Padding(
      padding: const EdgeInsets.only(bottom: 10),
      child: Material(
        color: AppColors.surfacePrimary,
        borderRadius: BorderRadius.circular(12),
        child: InkWell(
          borderRadius: BorderRadius.circular(12),
          onTap: () => context.push(RouteNames.ibLeadDetailPath(ib.id)),
          child: Container(
            padding: const EdgeInsets.all(14),
            decoration: BoxDecoration(
              borderRadius: BorderRadius.circular(12),
              border: Border.all(
                  color: AppColors.borderDefault.withValues(alpha: 0.5)),
            ),
            child: Row(
              children: [
                Container(
                  width: 3,
                  height: 48,
                  decoration: BoxDecoration(
                    color: statusColor,
                    borderRadius: BorderRadius.circular(2),
                  ),
                ),
                const SizedBox(width: 12),
                Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text(
                        ib.companyName,
                        style: AppTextStyles.labelLarge.copyWith(
                          fontWeight: FontWeight.w600,
                          fontSize: 14,
                        ),
                        maxLines: 1,
                        overflow: TextOverflow.ellipsis,
                      ),
                      const SizedBox(height: 4),
                      Text(
                        ib.dealValue != null
                            ? IndianCurrencyFormatter.shortForm(ib.dealValue!)
                            : ib.dealValueRange.label,
                        style: AppTextStyles.labelLarge.copyWith(
                          color: AppColors.navyPrimary,
                          fontWeight: FontWeight.w700,
                          fontSize: 15,
                        ),
                      ),
                      const SizedBox(height: 2),
                      Text(
                        '${ib.dealType.label} · ${ib.timelineDisplay}',
                        style: AppTextStyles.caption
                            .copyWith(color: AppColors.textHint),
                      ),
                    ],
                  ),
                ),
                Container(
                  padding:
                      const EdgeInsets.symmetric(horizontal: 8, vertical: 3),
                  decoration: BoxDecoration(
                    color: statusColor.withValues(alpha: 0.12),
                    borderRadius: BorderRadius.circular(20),
                  ),
                  child: Text(
                    ib.status.label,
                    style: AppTextStyles.caption.copyWith(
                      color: statusColor,
                      fontWeight: FontWeight.w700,
                      fontSize: 10.5,
                    ),
                  ),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}

class _SentBackStrip extends StatelessWidget {
  final List<IbLeadModel> leads;
  const _SentBackStrip({required this.leads});

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.fromLTRB(12, 10, 12, 10),
      decoration: BoxDecoration(
        color: AppColors.errorRed.withValues(alpha: 0.08),
        borderRadius: BorderRadius.circular(12),
        border: Border.all(color: AppColors.errorRed.withValues(alpha: 0.35)),
      ),
      child: Row(
        children: [
          const Icon(Icons.replay_circle_filled,
              color: AppColors.errorRed, size: 18),
          const SizedBox(width: 8),
          Expanded(
            child: Text(
              '${leads.length} sent back — needs your action',
              style: AppTextStyles.bodySmall.copyWith(
                color: AppColors.errorRed,
                fontWeight: FontWeight.w700,
              ),
            ),
          ),
          TextButton(
            onPressed: () => context.push(
                RouteNames.ibLeadDetailPath(leads.first.id)),
            style: TextButton.styleFrom(
              minimumSize: Size.zero,
              padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),
              tapTargetSize: MaterialTapTargetSize.shrinkWrap,
              foregroundColor: AppColors.errorRed,
            ),
            child: const Text('Open'),
          ),
        ],
      ),
    );
  }
}

class _StatusFilterBar extends StatelessWidget {
  final IbLeadStatus? value;
  final ValueChanged<IbLeadStatus?> onChanged;
  final Map<IbLeadStatus, int> counts;
  const _StatusFilterBar({
    required this.value,
    required this.onChanged,
    required this.counts,
  });

  @override
  Widget build(BuildContext context) {
    return SizedBox(
      height: 36,
      child: ListView(
        scrollDirection: Axis.horizontal,
        children: [
          _chip('All', value == null, () => onChanged(null)),
          const SizedBox(width: 6),
          for (final s in IbLeadStatus.values) ...[
            _chip(
              counts[s] == null ? s.label : '${s.label}  ${counts[s]}',
              value == s,
              () => onChanged(s),
            ),
            const SizedBox(width: 6),
          ],
        ],
      ),
    );
  }

  Widget _chip(String label, bool selected, VoidCallback onTap) {
    return InkWell(
      onTap: onTap,
      borderRadius: BorderRadius.circular(20),
      child: Container(
        padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 7),
        decoration: BoxDecoration(
          color: selected
              ? AppColors.navyPrimary.withValues(alpha: 0.12)
              : AppColors.surfaceTertiary,
          borderRadius: BorderRadius.circular(20),
          border: Border.all(
            color: selected
                ? AppColors.navyPrimary.withValues(alpha: 0.4)
                : AppColors.borderDefault,
          ),
        ),
        child: Text(
          label,
          style: AppTextStyles.bodySmall.copyWith(
            color: selected ? AppColors.navyPrimary : AppColors.textSecondary,
            fontWeight: selected ? FontWeight.w700 : FontWeight.w500,
          ),
        ),
      ),
    );
  }
}
